web/router.ex
defmodule TomeStats.Router do
  use TomeStats.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TomeStats do
    pipe_through :browser # Use the default browser stack
    resources "search", SearchController, only: [:index, :create]
    resources "/search-keys", SearchKeyController
    resources "/search-key-values", SearchKeyValueController

    get "/", SearchController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", TomeStats.Api do
    pipe_through :api
    resources "/search-keys", SearchKeyController
    resources "/search-key-values", SearchKeyValueController
  end
end

web/views/layout_view.ex
defmodule TomeStats.LayoutView do
  use TomeStats.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tome Stats</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href='<%= search_key_url(TomeStats.Endpoint, :index) %>'>Search Keys</a><li>
          <li><a href='<%= search_key_value_url(TomeStats.Endpoint, :index) %>'>Search Key Values</a><li>
        </ul>
        <h1><a href='<%= search_path(TomeStats.Endpoint, :index) %>'>Tome Stats</a></h1>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>